version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weely'
      day: 'wednesday'
      time: '11:00'
      timezone: 'Europe/Belgrade'
    versioning-strategy: increase
